[package]
name = "rustfst-ffi"
version = "1.3.1"
authors = [
    "Emrick Sinitambirivoutin <emrick.sinitambirivoutin@sonos.com>",
    "Alexandre Caulier <alexandre.caulier@protonmail.com>"
]
license = 'MIT/Apache-2.0'
repository = 'https://github.com/garvys-org/rustfst'
edition = "2018"
description = 'Library for constructing, combining, optimizing, and searching weighted finite-state transducers (FSTs). Rustfst-ffi provides C interfaces of the Rust library'
documentation = 'https://docs.rs/rustfst'
readme = '../README.md'
keywords = [
    'FST',
    'graph',
    'transducer',
    'acceptor',
    'ffi'
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std", "rustfst-state-label-u32"]
rustfst-state-label-u32 = ["rustfst/state-label-u32"]
std = ["rustfst/std"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
# Vendored local version to remove libc dependency
ffi-convert = { path = "../ffi-convert" }
# Used locally when developping and used the one from crates.io when publishing
rustfst = { path = "../rustfst", version = "=1.3.1", default-features = false }
downcast-rs = "2"