name: Build OpenFST

on: workflow_dispatch

jobs:
  build-openfst:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: build
        run: ./build_openfst.sh
      - uses: actions/upload-artifact@v4
        with:
          name: openfst-1.7.2-${{ matrix.os }}
          path: openfst-1.7.2
          retention-days: 90