name: Embedded targets

on:
#  pull_request:
#  push:
#    branches:
#      - 'main'
#    tags:
#      - 'rustfst-v**'
#  schedule:
#    - cron:  '0 5 * * *'

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - raspbian
          - aarch64-unknown-linux-gnu
          - wasm32-unknown-unknown
            #          - armv6vfp-unknown-linux-gnueabihf
            #          - armv7-unknown-linux-gnueabihf
            #          - aarch64-linux-android
            #          - armv7-linux-androideabi
            #          - i686-linux-android
            #          - x86_64-linux-android

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cross script
      env:
        PLATFORM: ${{matrix.platform}}
        AWS_ACCESS_KEY_ID: ${{secrets.TRACT_CI_AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.TRACT_CI_AWS_SECRET_ACCESS_KEY}}
        AWS_EC2_METADATA_DISABLED: true
      run: .ci/cross.sh

      #  ios:
      #    strategy:
      #      fail-fast: false
      #      matrix:
      #        platform:
      #          - aarch64-apple-ios
      #
      #    runs-on: macOS-latest
      #
      #    steps:
      #    - uses: actions/checkout@v1
      #    - name: Cross script
      #      env:
      #        PLATFORM: ${{matrix.platform}}
      #      run: .travis/cross.sh
